
/**
 * The proxy server URL.
 */
export const PROXY_SERVER = 'https://learner-gateway.uc.r.appspot.com/';
// export const PROXY_SERVER = 'http://127.0.0.1:8080/';

/**
 * The firebase configuration. the apiKey is an id of the project, not a securit key, 
 * so it's okay to check in the code. This object is generated by Firebase service,
 * don't change any name and value of it.
 */
export const environment = {
  production: false,
  firebase: {
    apiKey: "AIzaSyClRfxf9Fa6vtgWZnvUJFiZTDYoOZlzzW0",
    authDomain: "pingeter-blogger.firebaseapp.com",
    projectId: "pingeter-blogger",
    storageBucket: "pingeter-blogger.firebasestorage.app",
    messagingSenderId: "1041397028813",
    appId: "1:1041397028813:web:ee065d4499b7a522091684",
    measurementId: "G-SV3PZ23CTE"
  },
  approvedEmails: ['youpingh@gmail.com', 'peterhu86@gmail.com', 'peter@TheGoodNeighbors.com', 'lanvong87@gmail.com'],
  proxy: PROXY_SERVER,
  services: {
    tts: PROXY_SERVER + 'tts',
    stt: PROXY_SERVER + 'stt',
    pinyin: PROXY_SERVER + 'pinyin'
  }
};
